export interface CompanyFinanceData {
  ticker: string;
  name: string;
  description: string;
  sector: string;
  industry: string;
  exchange: string;
  currency: string;
  marketCap: number;
  peRatio: number;
  dividendYield: number;
  beta: number;
  financials: {
    revenue: number[];
    netIncome: number[];
    operatingCashflow: number[];
    totalDebt: number[];
    totalCash: number[];
    years: string[];
  };
  metrics: {
    profitMargin: number;
    operatingMargin: number;
    returnOnEquity: number;
    revenueGrowth: number;
    ebitda: number;
    debtToEquity?: number;
  };
  currentPrice: number;
}

export interface MockReport {
  id: string;
  ticker: string;
  companyName: string;
  report: string;
  financialData: CompanyFinanceData;
  verdict?: string;
  investmentScore?: number;
  priceTarget?: string;
  risks?: string[];
  opportunities?: string[];
  reasoning?: string;
  newsArticles?: any[];
  chatReplies: { q: string; a: string }[];
  defaultChatReply: string;
}

export const MOCK_REPORTS: Record<string, MockReport> = {
  AAPL: {
    id: 'aapl-report-id',
    ticker: 'AAPL',
    companyName: 'Apple Inc.',
    report: `# EQUITY RESEARCH REPORT: APPLE INC. (AAPL)
*Generated by AI Investment Research Agent*

## 1. Executive Summary & Recommendation
- **Investment Recommendation**: **BUY** (Target Range: $195.00 - $210.00)
- **Current Price**: $182.30 USD
- **Core Investment Thesis**: Apple's premium brand moat, high-margin Services expansion, and robust share buybacks continue to generate premium returns. While hardware cycles are stabilizing, new spatial computing form factors and software integrations secure double-digit earnings growth.

## 2. Financial Performance & Trends
Apple continues to showcase exceptional balance sheet strength, yielding high returns on equity despite minor top-line hardware fluctuations:

| Metric | FY 2021 | FY 2022 | FY 2023 |
| :--- | :--- | :--- | :--- |
| **Revenue** | $365.8B | $394.3B | $383.3B |
| **Net Income** | $94.6B | $99.8B | $97.0B |
| **Operating Cashflow** | $104.0B | $122.1B | $110.5B |
| **Net Margin** | 25.8% | 25.3% | 25.3% |

*The growth in high-margin Services revenue (Apple Music, iCloud, Apple Pay) continues to offset incremental shifts in iPhone volume constraints.*

## 3. Qualitative Drivers & Sentiment
- **Consumer Moat**: Ecosystem lock-in through unified macOS/iOS integrations remains the strongest competitive advantage in the tech sector.
- **AI Innovations**: On-device neural engine deployments represent a solid pipeline catalyst for an upgrade cycle starting mid-2026.
- **Market Sentiment**: **Moderately Bullish** due to stable global demand and strong cash distributions to shareholders.

## 4. Strategic Risk Analysis (SWOT)
- **Strengths**: Leading global premium brand; massive liquidity ($162B cash + equivalents); unmatched ecosystem lock-in.
- **Weaknesses**: Dependency on hardware cycles (iPhone accounts for ~50% of revenue); slowing growth in hardware units.
- **Opportunities**: AI features upgrade cycle; expansion of fintech services (Apple Card, Pay Later); medical and AR wearables.
- **Threats**: Antitrust regulatory actions in US and EU; supply chain concentration in East Asia.

## 5. Valuation Analysis & Final Verdict
Apple trades at a trailing P/E of 28.5x, reflecting a premium relative to traditional tech but reasonable given its risk profile. Free cash flow conversion remains near 100%, justifying active capital deployment. We rate AAPL a **BUY** for long-term compound growth.`,
    financialData: {
      ticker: 'AAPL',
      name: 'Apple Inc.',
      description: 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.',
      sector: 'Technology',
      industry: 'Consumer Electronics',
      exchange: 'NASDAQ',
      currency: 'USD',
      marketCap: 2850000000000,
      peRatio: 28.5,
      dividendYield: 0.0052,
      beta: 1.28,
      financials: {
        revenue: [365817000000, 394328000000, 383285000000],
        netIncome: [94680000000, 99803000000, 96995000000],
        operatingCashflow: [104038000000, 122151000000, 110543000000],
        totalDebt: [124719000000, 120069000000, 111088000000],
        totalCash: [62639000000, 48304000000, 29965000000],
        years: ['2021', '2022', '2023']
      },
      metrics: {
        profitMargin: 0.2531,
        operatingMargin: 0.2982,
        returnOnEquity: 1.604,
        revenueGrowth: -0.028,
        ebitda: 125820000000,
        debtToEquity: 1.45
      },
      currentPrice: 182.30
    },
    chatReplies: [
      { q: 'margins', a: 'Apple maintains a Net Profit Margin of 25.31% and an Operating Margin of 29.82%. This premium margin is driven by high-margin software services (e.g. App Store, iCloud, Services subscriptions) which balance standard hardware manufacturing margins.' },
      { q: 'valuation', a: 'AAPL trades at a trailing P/E of 28.5x, which represents a historical premium. Given its predictable cash flows and massive share repurchase program, this multiple is considered fair by the research agent.' },
      { q: 'risks', a: 'The primary risks listed are regulatory threats (EU Digital Markets Act, DOJ anti-trust lawsuit) and supply chain concentration in East Asia. Apple is mitigating the latter by expanding operations to India and Vietnam.' },
      { q: 'buy', a: 'The recommendation is a BUY with a target price range of $195.00 - $210.00, driven by the upcoming AI-driven upgrade cycle and strong ecosystem moat.' }
    ],
    defaultChatReply: 'Apple is experiencing minor hardware growth deceleration, but its Services segment is expanding at double-digit rates, reinforcing its massive cash flows.'
  },
  TSLA: {
    id: 'tsla-report-id',
    ticker: 'TSLA',
    companyName: 'Tesla Inc.',
    report: `# EQUITY RESEARCH REPORT: TESLA INC. (TSLA)
*Generated by AI Investment Research Agent*

## 1. Executive Summary & Recommendation
- **Investment Recommendation**: **HOLD** (Target Range: $180.00 - $205.00)
- **Current Price**: $178.50 USD
- **Core Investment Thesis**: Tesla is navigating a challenging transition phase marked by vehicle price reductions, margin compression, and intensifying global EV competition. While long-term valuation is supported by autonomous driving, robotics, and energy storage, near-term delivery rates indicate cyclical headwinds.

## 2. Financial Performance & Trends
Tesla's automotive margin compression has led to bottom-line contraction despite ongoing delivery growth:

| Metric | FY 2021 | FY 2022 | FY 2023 |
| :--- | :--- | :--- | :--- |
| **Revenue** | $53.8B | $81.5B | $96.8B |
| **Net Income** | $5.5B | $12.6B | $15.0B |
| **Operating Cashflow** | $11.5B | $14.7B | $13.3B |
| **Net Margin** | 10.2% | 15.4% | 15.5% |

*The shift towards standard mass-market vehicles (Model Y/3) combined with price cuts has lowered automotive margins from peak levels of 30% down to roughly 17%.*

## 3. Qualitative Drivers & Sentiment
- **Energy Storage Momentum**: Tesla Energy deployment (Megapack) is growing at over 100% YoY, offering high-margin recurring software options.
- **Autopilot & FSD**: The launch of FSD v12 neural net technology provides long-term licensing opportunities but remains in beta.
- **Market Sentiment**: **Neutral** due to inventory accumulation and slowing global electric vehicle uptake.

## 4. Strategic Risk Analysis (SWOT)
- **Strengths**: Leading global EV brand; negative net debt structure ($29B cash vs $3B debt); industry-leading manufacturing cost structure.
- **Weaknesses**: CEO distraction risk; highly cyclical automotive margins; model pipeline age.
- **Opportunities**: Scaling Megapacks; next-gen cheap EV model ($25k platform); Robotaxi network launch.
- **Threats**: Extreme EV competition in China (BYD); subsidy reduction changes; sluggish global EV demand.

## 5. Valuation Analysis & Final Verdict
Tesla trades at 58.0x P/E, which is high compared to automakers but low historically for Tesla. Since margin stabilization is not yet assured, a **HOLD** recommendation is warranted. We advise waiting for clearer indicators of Model 2 timelines.`,
    financialData: {
      ticker: 'TSLA',
      name: 'Tesla Inc.',
      description: 'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems globally.',
      sector: 'Consumer Cyclical',
      industry: 'Auto Manufacturers',
      exchange: 'NASDAQ',
      currency: 'USD',
      marketCap: 568000000000,
      peRatio: 58.0,
      dividendYield: 0,
      beta: 2.1,
      financials: {
        revenue: [53823000000, 81462000000, 96773000000],
        netIncome: [55190000000, 12583000000, 14997000000],
        operatingCashflow: [11497000000, 14724000000, 13256000000],
        totalDebt: [7000000000, 4800000000, 3100000000],
        totalCash: [17576000000, 22185000000, 29094000000],
        years: ['2021', '2022', '2023']
      },
      metrics: {
        profitMargin: 0.155,
        operatingMargin: 0.092,
        returnOnEquity: 0.231,
        revenueGrowth: 0.188,
        ebitda: 14780000000,
        debtToEquity: 0.06
      },
      currentPrice: 178.50
    },
    chatReplies: [
      { q: 'margins', a: 'Tesla\'s Net profit margin sits at 15.5%. However, operating margin has compressed to 9.2% due to intense pricing wars in the EV space, particularly in China and Europe.' },
      { q: 'valuation', a: 'TSLA trades at a trailing P/E of 58x. This multiple prices TSLA as a technology and robotics leader rather than a pure car maker. Any failure to hit autonomy milestones presents valuation risk.' },
      { q: 'autonomy', a: 'Autonomy and FSD v12 represent Tesla\'s largest strategic opportunity. Success in Robotaxi software licensing could drive high-margin licensing streams equivalent to software-as-a-service models.' },
      { q: 'hold', a: 'The HOLD recommendation is based on automotive margin stabilization uncertainty and near-term delivery bottlenecks, balancing Megapack energy storage catalysts.' }
    ],
    defaultChatReply: 'Tesla is shifting focus from high-volume vehicle scaling to FSD autonomy and energy storage deployment, which are higher margin vectors.'
  },
  NVDA: {
    id: 'nvda-report-id',
    ticker: 'NVDA',
    companyName: 'NVIDIA Corporation',
    report: `# EQUITY RESEARCH REPORT: NVIDIA CORP. (NVDA)
*Generated by AI Investment Research Agent*

## 1. Executive Summary & Recommendation
- **Investment Recommendation**: **BUY** (Target Range: $950.00 - $1,100.00)
- **Current Price**: $875.12 USD
- **Core Investment Thesis**: NVIDIA is the undisputed market leader in AI accelerators (H100/H200/Blackwell), capturing over 90% of the datacenter chip segment. Its proprietary CUDA software ecosystem creates an insurmountable competitive moat, translating hyper-scale AI capital expenditure directly into net income.

## 2. Financial Performance & Trends
NVIDIA has demonstrated unprecedented hyper-growth, expanding datacenters revenue by over 200% YoY:

| Metric | FY 2022 | FY 2023 | FY 2024 |
| :--- | :--- | :--- | :--- |
| **Revenue** | $26.9B | $27.0B | $60.9B |
| **Net Income** | $9.7B | $4.4B | $29.8B |
| **Operating Cashflow** | $9.1B | $5.6B | $28.1B |
| **Net Margin** | 36.2% | 16.2% | 48.8% |

*The Blackwell chip launch is projected to extend this hyper-growth path through FY 2026, supported by massive pre-orders from tech giants.*

## 3. Qualitative Drivers & Sentiment
- **Blackwell Dominance**: The newly launched GPU architecture offers 30x performance gains for LLM inference at significantly lower energy limits.
- **Software Moat**: Over 5 million active developers using NVIDIA CUDA software locks clients in, rendering switching costs high.
- **Market Sentiment**: **Extremely Bullish** due to relentless capital allocations from cloud hyper-scalers (Microsoft, AWS, Meta).

## 4. Strategic Risk Analysis (SWOT)
- **Strengths**: CUDA software lock-in; industry-leading margins (48.8% net); undisputed AI market share.
- **Weaknesses**: Supply chain bottlenecks (reliance on TSMC packaging); high customer concentration.
- **Opportunities**: Autonomous driving compute units; enterprise software suites; sovereign AI infrastructure projects.
- **Threats**: Custom ASIC development by customers (TPUs, Trainium); trade compliance limits; semiconductor cyclicality.

## 5. Valuation Analysis & Final Verdict
Trading at a trailing P/E of 72.0x, the multiple appears rich but is reasonable when matched to its forward growth rate (PEG < 1.0). Given Blackwell pre-orders, we rate NVDA a **BUY** for high-growth portfolios.`,
    financialData: {
      ticker: 'NVDA',
      name: 'NVIDIA Corporation',
      description: 'NVIDIA Corporation focuses on personal computer graphics, graphics processing units, and also artificial intelligence solutions.',
      sector: 'Technology',
      industry: 'Semiconductors',
      exchange: 'NASDAQ',
      currency: 'USD',
      marketCap: 2180000000000,
      peRatio: 72.0,
      dividendYield: 0.0002,
      beta: 1.85,
      financials: {
        revenue: [26914000000, 26974000000, 60922000000],
        netIncome: [9752000000, 4368000000, 29760000000],
        operatingCashflow: [9108000000, 5641000000, 28090000000],
        totalDebt: [10940000000, 11010000000, 9700000000],
        totalCash: [21208000000, 13296000000, 25980000000],
        years: ['2022', '2023', '2024']
      },
      metrics: {
        profitMargin: 0.4885,
        operatingMargin: 0.5412,
        returnOnEquity: 0.915,
        revenueGrowth: 1.258,
        ebitda: 34480000000,
        debtToEquity: 0.22
      },
      currentPrice: 875.12
    },
    chatReplies: [
      { q: 'margins', a: 'NVIDIA operates at a massive Net Profit Margin of 48.85% and an Operating Margin of 54.12%, showcasing the extreme pricing power they hold over datacenter chips.' },
      { q: 'valuation', a: 'NVDA trades at a trailing P/E of 72.0x. Although high, the forward P/E is compressed below 30x due to exponential earnings projections, making it value-attractive relative to growth.' },
      { q: 'competitors', a: 'The primary competitors are custom ASICs built by hyperscalers (e.g. Google TPU, Amazon Trainium) and AMD\'s Instinct series (MI300X). However, NVIDIA\'s CUDA software provides a significant moat.' },
      { q: 'buy', a: 'The BUY recommendation is driven by Blackwell\'s performance capabilities and the continuing cloud datacenter CapEx boom.' }
    ],
    defaultChatReply: 'NVIDIA continues to sustain near-monopoly positions in AI training hardware compute, with demand outstripping supply for the next 12 months.'
  }
};
